

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/9.3.0/userguide/building_cpp_projects.html in the Gradle documentation.
 */


// // Define paths
// val openclPath = "C:/Users/tomhb/University/OpenCL/OpenCL-SDK/install"
// val localLibPath = "C:/Users/tomhb/University/cs310/FallingSandIter1/app/src/main/headers"
//
// tasks.withType(CppCompile::class).configureEach {
//     compilerArgs.add("-I${openclPath}/include")
//     compilerArgs.add("-I${localLibPath}/include")
//
//     // No GLEW_STATIC define (using dynamic)
//     // No GLFW_STATIC define (using static GLFW)
//
//     compilerArgs.add("-g")
//     compilerArgs.add("-O0")
//     compilerArgs.add("/GS-")
// }
//
// tasks.withType(LinkExecutable::class).configureEach {
//     // Dynamic GLEW (requires DLL)
//     linkerArgs.add("${localLibPath}/lib/glew32.lib")
//
//     // Static GLFW
//     linkerArgs.add("${localLibPath}/lib/glfw3.lib")
//
//     // OpenCL
//     linkerArgs.add("${openclPath}/lib/OpenCL.lib")
//
//     // Windows system libraries
//     linkerArgs.add("user32.lib")
//     linkerArgs.add("gdi32.lib")
//     linkerArgs.add("shell32.lib")
//     linkerArgs.add("ole32.lib")
//     linkerArgs.add("winmm.lib")
//     linkerArgs.add("ws2_32.lib")
//     linkerArgs.add("opengl32.lib")
//     linkerArgs.add("advapi32.lib")
//
//     // C runtime
//     linkerArgs.add("msvcrt.lib")
//     linkerArgs.add("ucrt.lib")
//     linkerArgs.add("vcruntime.lib")
// }
//
// // Copy glew32.dll to executable directory
// tasks.register<Copy>("copyGlewDll") {
//     dependsOn(tasks.build)
//
//     val dllSource = file("${localLibPath}/bin/glew32.dll")
//     val exeDir = file("app/build/exe/main/debug")
//
//     if (dllSource.exists()) {
//         from(dllSource)
//         into(exeDir)
//         println("✓ glew32.dll will be copied to executable directory")
//     } else {
//         println("⚠ Warning: glew32.dll not found at ${dllSource.absolutePath}")
//         println("  The program may not run correctly.")
//     }
// }
//
// // Run task
// tasks.register<Exec>("run") {
//     dependsOn(tasks.build, tasks.named("copyGlewDll"))
//
//     val exePath = file("build/exe/main/debug/app.exe")
//     commandLine("cmd", "/c", exePath.absolutePath)
//
//     // Set to ignore exit code if needed
//     // ignoreExitValue = false
// }


plugins {
    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Set the target operating system and architecture for this application
application {
    source.from(file("src/main/cpp"))
    privateHeaders.from(file("src/main/headers"))
    targetMachines.add(machines.windows.x86_64)
}



// Direct linking to your OpenCL installation
tasks.withType(CppCompile::class).configureEach {
    // Add your OpenCL include path
    compilerArgs.add("-IC:/Users/tomhb/University/OpenCL/OpenCL-SDK/install/include")
    compilerArgs.add("-IC:/Users/tomhb/University/cs310/FallingSandIter1/app/src/main/headers/include")

    compilerArgs.add("-DGLEW_STATIC")
    compilerArgs.add("-DGLFW_STATIC")

}


tasks.withType(LinkExecutable::class).configureEach {
    // Add your OpenCL library path and library

    linkerArgs.add("C:/Users/tomhb/University/cs310/FallingSandIter1/app/src/main/headers/lib/glew32s.lib")
    // linkerArgs.add("C:/Users/tomhb/University/cs310/FallingSandIter1/app/build/exe/main/debug/glew32.dll")
    linkerArgs.add("C:/Users/tomhb/University/OpenCL/OpenCL-SDK/install/lib/OpenCL.lib")
    linkerArgs.add("C:/Users/tomhb/University/cs310/FallingSandIter1/app/src/main/headers/lib/glfw3.lib")

    // Add required Windows system libraries for GLFW
    linkerArgs.add("user32.lib")     // Windows API functions
    linkerArgs.add("gdi32.lib")      // Graphics device interface
    linkerArgs.add("shell32.lib")    // Shell API
    linkerArgs.add("ole32.lib")      // OLE/com libraries

    // For GLFW's Win32 platform layer
    linkerArgs.add("winmm.lib")      // Multimedia (joystick, timers)
    linkerArgs.add("ws2_32.lib")     // Windows sockets

    // C runtime and standard libraries
    linkerArgs.add("msvcrt.lib")     // C runtime library
    linkerArgs.add("ucrt.lib")       // Universal CRT
    linkerArgs.add("vcruntime.lib")  // Visual C++ runtime

    // Additional libraries that might be needed
    linkerArgs.add("opengl32.lib")   // OpenGL (if using OpenGL context)
    linkerArgs.add("advapi32.lib")   // Advanced Windows API
}

tasks.register<Exec>("run") {
    dependsOn(tasks.build)  // Build first

    // For Windows
    val exePath = "C:/Users/tomhb/University/cs310/FallingSandIter1/app/build/exe/main/debug/app.exe"  // Adjust path as needed
    commandLine("cmd", "/c", exePath)

    // For cross-platform:
    // commandLine(exePath)
}

// Make 'run' the default task when no arguments are provided
defaultTasks("build", "run")
