/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/9.3.0/userguide/building_cpp_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Set the target operating system and architecture for this application
application {

    source.from(file("src/main/cpp"))

    privateHeaders.from(file("src/main/headers"))

    targetMachines.add(machines.windows.x86_64)
}

// Direct linking to your OpenCL installation
tasks.withType(CppCompile::class).configureEach {
    // Add your OpenCL include path
    compilerArgs.add("-IC:/Users/tomhb/University/OpenCL/OpenCL-SDK/install/include")
    // Or if you have include/CL structure:
    // compilerArgs.add("-IC:/path/to/your/opencl")
}

tasks.withType(LinkExecutable::class).configureEach {
    // Add your OpenCL library path and library
    val openclLibPath = "C:/Users/tomhb/University/OpenCL/OpenCL-SDK/install/lib/OpenCL.lib"  // For Windows .lib file
    // OR for the .dll:
    // linkerArgs.add("C:/path/to/your/opencl/bin/OpenCL.dll")
    
    linkerArgs.add(openclLibPath)
}
