/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/9.3.0/userguide/building_cpp_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Set the target operating system and architecture for this application
application {

    source.from(file("src/main/cpp"))

    privateHeaders.from(file("src/main/headers"))

    targetMachines.add(machines.windows.x86_64)
}

// Direct linking to your OpenCL installation
tasks.withType(CppCompile::class).configureEach {
    // Add your OpenCL include path
    compilerArgs.add("-IC:/Users/tomhb/University/OpenCL/OpenCL-SDK/install/include")
    compilerArgs.add("-IC:/Users/tomhb/University/cs310/FallingSandIter1/app/src/main/headers/include")

}

tasks.withType(LinkExecutable::class).configureEach {
    // Add your OpenCL library path and library
    
    linkerArgs.add("C:/Users/tomhb/University/OpenCL/OpenCL-SDK/install/lib/OpenCL.lib")
    linkerArgs.add("C:/Users/tomhb/University/cs310/FallingSandIter1/app/src/main/headers/lib/glfw3.lib")

    // Add required Windows system libraries for GLFW
    linkerArgs.add("user32.lib")     // Windows API functions
    linkerArgs.add("gdi32.lib")      // Graphics device interface
    linkerArgs.add("shell32.lib")    // Shell API
    linkerArgs.add("ole32.lib")      // OLE/com libraries
    
    // For GLFW's Win32 platform layer
    linkerArgs.add("winmm.lib")      // Multimedia (joystick, timers)
    linkerArgs.add("ws2_32.lib")     // Windows sockets
    
    // C runtime and standard libraries
    linkerArgs.add("msvcrt.lib")     // C runtime library
    linkerArgs.add("ucrt.lib")       // Universal CRT
    linkerArgs.add("vcruntime.lib")  // Visual C++ runtime
    
    // Additional libraries that might be needed
    linkerArgs.add("opengl32.lib")   // OpenGL (if using OpenGL context)
    linkerArgs.add("advapi32.lib")   // Advanced Windows API
}
